l_simp_chinese:
 pm_government_run_building_steel_industry: "政府运营" 
 pm_government_run_building_motor_industries: "政府运营"
pm_government_run_building_munition_plants: "政府运营"
 pmg_ownership_capital_building_steel_mills: "所有制"
 pmg_ownership_capital_building_motor_industry: "所有制"
